name: update-data
on:
  schedule:
    - cron: "2 * * * *"
  workflow_dispatch:
jobs:
  update-data:
    name: "Update Data"
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      # - name: Create dot env file
      #   run: echo "${{ secrets.ENV_SHEETSON }}" > .env
      - name: Update Data
        run: yarn install && yarn update-data
        env:
          ENV_SHEETSON: ${{ secrets.ENV_SHEETSON }}
        working-directory: fetcher/
      - name: Commit
        uses: EndBug/add-and-commit@v6
        with:
          message: "Update Data"
          push: true

    # env:
    #   ENV_SHEETSON: ${{ secrets.ENV_SHEETSON }}
